CREATE DATABASE GameHub;
USE GameHub;

-- Done
CREATE TABLE CUSTOMER (
    CUS_ID INT(4) PRIMARY KEY,
    CUS_FNAME VARCHAR(30) NOT NULL,
    CUS_LNAME VARCHAR(30) NOT NULL,
    CUS_EMAIL VARCHAR(30) NOT NULL UNIQUE,
    CUS_ADDRESS VARCHAR(30) NOT NULL
);

-- Done
CREATE TABLE VENDOR (
    VENDOR_ID INT(4) PRIMARY KEY,
    VENDOR_NAME VARCHAR(20) NOT NULL, 
    VENDOR_PHONE VARCHAR(30)
);

-- Done
CREATE TABLE CATEGORY (
    CAT_ID INT(4) PRIMARY KEY,
    CAT_NAME VARCHAR(20) NOT NULL
);

-- Done
CREATE TABLE PRODUCT (
    PROD_ID INT(4) PRIMARY KEY,
    PROD_NAME VARCHAR(20) NOT NULL,
    PROD_PRICE DECIMAL(6,2) NOT NULL,
    VENDOR_ID INT(4) NOT NULL,
    CAT_ID INT(4) NOT NULL,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID),
    FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID)
);

-- Done
CREATE TABLE GAME_GENRE (
    GENRE_ID INT(4) PRIMARY KEY,
    GENRE_NAME VARCHAR(30) NOT NULL
);

-- Done
CREATE TABLE PLATFORM (
    PLATFORM_ID INT(4) PRIMARY KEY,
    PLATFORM_NAME VARCHAR(20) NOT NULL
);

-- Done
CREATE TABLE PRODUCT_GENRE (
    PROD_ID INT(4) NOT NULL,
    GENRE_ID INT(4) NOT NULL,
    PRIMARY KEY (PROD_ID, GENRE_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GAME_GENRE(GENRE_ID)
);

-- Done
CREATE TABLE PHYSICAL_PROD (
    PROD_ID INT(4) PRIMARY KEY,
    SHIPPING_WEIGHT DECIMAL(10,2),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

-- Done
CREATE TABLE SUBSCRIPTION_PROD (
    PROD_ID INT(4) PRIMARY KEY,
    DURATION VARCHAR(15),
    SUB_TYPE VARCHAR(15),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

-- Done
CREATE TABLE DIGITAL_PROD (
    PROD_ID INT(4) PRIMARY KEY,
    PLATFORM_ID INT(4) NOT NULL,
    DOWNLOAD_SIZE VARCHAR(10),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID),
    FOREIGN KEY (PLATFORM_ID) REFERENCES PLATFORM(PLATFORM_ID)
);

-- Done
CREATE TABLE INVENTORY (
    PROD_ID INT(4) PRIMARY KEY,
    QTY_AVAILABLE INT(5) NOT NULL,
    LAST_UPDATED DATE,
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

-- Done
CREATE TABLE INVOICE (
    INV_ID INT(4) PRIMARY KEY,
    INV_DATE DATE NOT NULL,
    INV_TOTAL DECIMAL(8,2), -- Derived
    CUS_ID INT(4) NOT NULL,
    FOREIGN KEY (CUS_ID) REFERENCES CUSTOMER(CUS_ID)
);

-- Done
CREATE TABLE INVOICE_ITEM (
    INV_ITEM_ID INT(4) PRIMARY KEY,
    QUANTITY INT(5) NOT NULL,
    PRICE DECIMAL(8,2) NOT NULL,
    INV_ID INT(4) NOT NULL,
    PROD_ID INT(4) NOT NULL,
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID),
    FOREIGN KEY (PROD_ID) REFERENCES PRODUCT(PROD_ID)
);

-- Done
CREATE TABLE PAYMENT (
    PAYMENT_ID INT(4) PRIMARY KEY,
    PAYMENT_TYPE VARCHAR(15), 
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_AMOUNT DECIMAL(8,2) NOT NULL,
    INV_ID INT(4) NOT NULL,
    FOREIGN KEY (INV_ID) REFERENCES INVOICE(INV_ID)
);

-- Done
-- Manual data entry (filldb data generation had errors)
INSERT INTO PRODUCT_GENRE (PROD_ID, GENRE_ID)
SELECT 
    p.PROD_ID,
    ((p.PROD_ID + g.offset) % 8) + 1 AS GENRE_ID
FROM 
    PRODUCT p
JOIN (
    SELECT 0 AS 'offset' UNION ALL
    SELECT 1
) g
WHERE p.PROD_ID <= 400;

-- Pg6
SELECT 
    i.INV_ID,
    i.INV_DATE,
    c.CUS_FNAME,
    c.CUS_LNAME,
    ii.PROD_ID,
    ii.QUANTITY,
    ii.PRICE
FROM INVOICE i
JOIN CUSTOMER c ON i.CUS_ID = c.CUS_ID
JOIN INVOICE_ITEM ii ON i.INV_ID = ii.INV_ID
WHERE c.CUS_FNAME = 'Deshawn'
  AND c.CUS_LNAME = 'Breitenberg'
  AND i.INV_DATE = '2025-12-11';

-- Pg7
SELECT 
    p.PROD_ID,
    p.PROD_NAME,
    inv.QTY_AVAILABLE,
    SUM(ii.QUANTITY) AS TOTAL_SOLD
FROM PRODUCT p
JOIN INVENTORY inv ON p.PROD_ID = inv.PROD_ID
JOIN INVOICE_ITEM ii ON p.PROD_ID = ii.PROD_ID
JOIN INVOICE i ON ii.INV_ID = i.INV_ID
WHERE i.INV_DATE BETWEEN '2025-01-01' AND '2025-03-01'
GROUP BY p.PROD_ID, p.PROD_NAME, inv.QTY_AVAILABLE;

-- Pg8
SELECT 
    p.PROD_ID,
    p.PROD_NAME,
    inv.QTY_AVAILABLE,
    ph.SHIPPING_WEIGHT
FROM PRODUCT p
JOIN PHYSICAL_PROD ph ON p.PROD_ID = ph.PROD_ID
JOIN INVENTORY inv ON p.PROD_ID = inv.PROD_ID;

-- Pg9
CREATE PROCEDURE GetCustomerInvoices(IN customer_id INT)
BEGIN
    SELECT 
        c.CUS_FNAME,
        c.CUS_LNAME,
        i.INV_ID,
        i.INV_DATE,
        SUM(ii.QUANTITY * ii.PRICE) AS TOTAL
    FROM CUSTOMER c
    JOIN INVOICE i ON c.CUS_ID = i.CUS_ID
    JOIN INVOICE_ITEM ii ON i.INV_ID = ii.INV_ID
    WHERE c.CUS_ID = customer_id
    GROUP BY i.INV_ID;
END;

CALL GetCustomerInvoices(434);

-- Pg10
INSERT INTO PRODUCT (PROD_ID, PROD_NAME, PROD_PRICE, VENDOR_ID, CAT_ID)
VALUES (501, 'New Game X', 59.99, 1, 2);

SELECT * FROM PRODUCT WHERE PROD_ID = 501;

-- Pg11
INSERT INTO INVOICE (INV_ID, INV_DATE, INV_TOTAL, CUS_ID)
VALUES (501, '2025-04-01', 0, 10);
INSERT INTO INVOICE_ITEM (INV_ITEM_ID, QUANTITY, PRICE, INV_ID, PROD_ID)
VALUES (2001, 2, 59.99, 501, 1);

UPDATE INVOICE
SET INV_TOTAL = (
    SELECT SUM(QUANTITY * PRICE)
    FROM INVOICE_ITEM
    WHERE INV_ID = 501
)
WHERE INV_ID = 501;

-- Pg12
CREATE VIEW CustomerPurchases AS
SELECT 
    c.CUS_ID,
    c.CUS_FNAME,
    c.CUS_LNAME,
    i.INV_ID,
    i.INV_DATE,
    ii.PROD_ID,
    ii.QUANTITY
FROM CUSTOMER c
JOIN INVOICE i ON c.CUS_ID = i.CUS_ID
JOIN INVOICE_ITEM ii ON i.INV_ID = ii.INV_ID;

SELECT * FROM CustomerPurchases;

-- Pg13
SELECT 
    c.CUS_ID,
    c.CUS_FNAME,
    COUNT(*) AS PURCHASE_COUNT,
    AVG(ii.PRICE) AS AVG_PRICE,
    MAX(ii.PRICE) AS MAX_PRICE
FROM CUSTOMER c
JOIN INVOICE i ON c.CUS_ID = i.CUS_ID
JOIN INVOICE_ITEM ii ON i.INV_ID = ii.INV_ID
WHERE ii.PRICE > 50
GROUP BY c.CUS_ID, c.CUS_FNAME
ORDER BY MAX(ii.PRICE) DESC
LIMIT 3;

-- Pg14
SELECT 
    PROD_ID,
    PROD_NAME,
    PROD_PRICE,
    PROD_PRICE * 1.10 AS PRICE_WITH_TAX
FROM PRODUCT
WHERE PROD_PRICE > (
    SELECT AVG(PROD_PRICE) FROM PRODUCT
);

-- Pg15
EXPLAIN SELECT 
    c.CUS_FNAME,
    p.PROD_NAME,
    i.INV_DATE,
    ii.QUANTITY,
    pay.PAYMENT_AMOUNT
FROM CUSTOMER c
JOIN INVOICE i ON c.CUS_ID = i.CUS_ID
JOIN INVOICE_ITEM ii ON i.INV_ID = ii.INV_ID
JOIN PRODUCT p ON ii.PROD_ID = p.PROD_ID
JOIN PAYMENT pay ON i.INV_ID = pay.INV_ID
WHERE ii.QUANTITY > 1
  AND pay.PAYMENT_AMOUNT > 20
  AND i.INV_DATE > '2025-01-01';

CREATE INDEX idx_invoice_date ON INVOICE(INV_DATE);
CREATE INDEX idx_payment_amount ON PAYMENT(PAYMENT_AMOUNT);
CREATE INDEX idx_quantity ON INVOICE_ITEM(QUANTITY);

-- Pg16
DESCRIBE CUSTOMER;
DESCRIBE PRODUCT;
DESCRIBE INVOICE;
DESCRIBE INVOICE_ITEM;
DESCRIBE PAYMENT;